# frozen_string_literal: true

# RecordingStudioCommentable initializer
# Generated by: rails generate recording_studio_commentable:install

RecordingStudioCommentable.configure do |config|
  # Timeout for service operations (seconds)
  # config.timeout = 5

  # Optional host-app layout. Leave blank to use Recording Studio's default layout.
  # config.layout = "recording_studio/default_layout"

  # Use recording_studio_trashable's namespaced trash API for comment deletion.
  # Leave false unless the host app installs recording_studio_trashable.
  config.use_recording_studio_trashable_for_destroy = false

  # Comment editor mode: false, :toolbar, or :selection.
  # true is supported as a backwards-compatible alias for :toolbar.
  config.rich_text_comments = false

  # Configure which attribute each recordable type should use for display labels.
  # Example: { "Page" => :title, "Event" => :event_name }
  config.recordable_display_attributes = {}

  # Configure which attribute or method each author type should use for display names.
  # Methods are supported, for example: { "User" => :full_name }
  config.author_display_attributes = {}

  # Configure which attribute or method each author type should use for avatar URLs.
  config.author_avatar_attributes = {}
end
