# frozen_string_literal: true

# RecordingStudioCommentable initializer
# Generated by: rails generate recording_studio_commentable:install

RecordingStudioCommentable.configure do |config|
  # Timeout for service operations (seconds)
  # config.timeout = 5

  # Enable FlatPack rich text editing for comment bodies.
  config.rich_text_comments = false
end
